import { PropsWithChildren } from 'react'
import { Roboto } from 'next/font/google'

import 'react-loading-skeleton/dist/skeleton.css'
import './globals.css'
import 'leaflet/dist/leaflet.css'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700', '900'],
})

export const metadata = {
  title: 'iClima - Verifique a temperatura',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <div className="weather-app-container">{children}</div>
      </body>
    </html>
  )
}

// Conta => rcapeto/raphaelcapetto@hotmail.com senha: @AplicativoWeatherApp
